README.md

Akil's name added to readme

---

README.md

Added Michael to README.md

---

.travis.yml
package-lock.json
package.json

setting up basic project name before travis setup.

---

README.md

added name - carlos

---

.travis.yml

travis activate deployment

---

client/components/auth-form.js
client/index.js

Ci test (accept to confirm ci)

---

.travis.yml
README.md
client/index.js
script/seed.js
server/db/models/index.js
server/db/models/shoe.js
server/db/models/user.js

Define models

---

script/seed.js
seedData/order.js

Order model

---

client/store/index.js
client/store/shoes.js

added basic redux for shoes (action types, creators, thunks, reducer)

---

client/store/shoes.js

added reducer to the combined reducer

---

client/components/SingleShoe.js

SingleShoe react component basic setup

---

server/db/models/index.js
server/db/models/order.js
server/db/models/user.js

Set up Oauth credentials

---

public/index.html
script/seed.js
server/db/models/OrderShoes.js
server/db/models/index.js

OrderShoes seeded with associations

---

script/seed.js
server/auth/google.js

Set associations between User & Order

---

client/components/allShoes.js
client/store/cart.js
client/store/order.js
server/api/index.js
server/api/orders.js
server/api/users.js
server/db/models/order.js

Login order

---

server/api/orders.js

Shopping cart

---

client/components/Cart.js
client/store/order.js
server/api/orders.js

cart remove and add/minus working!

---

seedData/shoes.js
server/db/models/order.js
server/db/models/shoe.js

Scrubbed data categories

---

client/components/allShoes.js
client/store/shoes.js
server/api/shoes.js

Shoes by category

---

client/components/Cart.js
client/components/allShoes.js
client/store/cart.js
client/store/index.js
client/store/order.js
server/api/index.js
server/api/orders.js

Shopping cart - fixed

---

client/components/SingleShoe.js

Add to cart for single shoe
